In [5]:
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
df = pd.read_csv("gnn_eval_results.csv")
df

     corpus_size  run  episode  sum_reward
0              5  NaN        1     -0.4060
1              5  NaN        2     -0.5100
2              5  NaN        3     -0.3400
3              5  NaN        4      0.0000
4              5  NaN        5     -0.3520
..           ...  ...      ...         ...
507           40  NaN      124     -0.9583
508           40  NaN      125      0.2655
509           40  NaN      126      0.4824
510           40  NaN      127     -2.4954
511           40  NaN      128     -1.0572

[512 rows x 4 columns]

In [7]:
df

     corpus_size  run  episode  sum_reward
0              5  NaN        1     -0.4060
1              5  NaN        2     -0.5100
2              5  NaN        3     -0.3400
3              5  NaN        4      0.0000
4              5  NaN        5     -0.3520
..           ...  ...      ...         ...
507           40  NaN      124     -0.9583
508           40  NaN      125      0.2655
509           40  NaN      126      0.4824
510           40  NaN      127     -2.4954
511           40  NaN      128     -1.0572

[512 rows x 4 columns]

In [8]:
avg_episode_total_rewards = (
    df.groupby(["corpus_size"])["sum_reward"]
    .mean()
    .reset_index()
    .rename(columns={"sum_reward": "average total reward"})
)
avg_episode_total_rewards

   corpus_size  average total reward
0            5             -0.243922
1           10             -0.064822
2           20             -0.986538
3           40             -1.162666

In [16]:
avg_episode_total_rewards = (
    df.groupby(["corpus_size"])["sum_reward"]
    .mean()
    .reset_index()
    .rename(columns={"sum_reward": "average total reward"})
)

avg_episode_total_rewards

   corpus_size  average total reward
0            5             -0.422429
1           10             -0.083455
2           20             -0.732781
3           40             -1.019630